# Project information
site_name: OSTFD 
site_url: https://opendatamanchester.github.io/OSTFD/
site_author: Open Data Manchester CIC
site_description: OSTFD is an open standard for textiles and fashion data.

# Repository
repo_name: ODM/OSTFD
repo_url: https://github.com/OpenDataManchester/OSTFD

# Copyright
copyright: Copyright &copy; Open Data Manchester CIC, and released under the Apache License, Version 2.0.

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default
      primary: green
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: green
      accent: cyan 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.indexes
    # - toc.integrate
    - navigation.top
    - navigation.path
    - navigation.footer
    - navigation.tabs
    - content.code.copy
    - content.tooltips

# Page Tree
nav:
  - Home: index.md
  - Start Here: 
    - Start Here: start-here/index.md
    - Key Concepts: start-here/key-concepts.md
    - Data Flow: start-here/data-flow.md
    - Data Architecture: start-here/data-architecture.md
  # - Data Formats: 2_Data_Formats/2_1_Data_Formats.md
  - Identifiers: identifiers/index.md
  - Core Schemas:
    - Core Schemas: schema/index.md
    - Base Materials: schema/base-materials.md
    - Materials: schema/materials.md
    - Components: schema/components.md
    - Fashion and Textile Products: schema/fashion-and-textile-products.md
    - Multipack: schema/multipacks.md
    - Loads: schema/loads.md
  - Constituents Lists:
    - Constituents Lists: constituent-lists/index.md
    - Material Constituents: constituent-lists/material-constituents.md
    - Component Constituents: constituent-lists/component-constituents.md
    - Product Constituents: constituent-lists/product-constituents.md
    - Multipack Constituents: constituent-lists/multipack-constituents.md
    - Load Constituents: constituent-lists/load-constituents.md
  - Relationship Lists:
    - Relationship Lists: relationship-lists/index.md
    - Care Label Claims: relationship-lists/care-label-claims.md
    - Certification Claims: relationship-lists/certification-claims.md
    - Component End of Life Routes: relationship-lists/component-end-of-life-routes.md
    - Measurements: relationship-lists/measurements.md
    - Organisations: relationship-lists/organisations.md
    - Product End of Life Routes: relationship-lists/product-end-of-life-routes.md
    - Recyclability Claims: relationship-lists/recyclability-claims.md
    - Recycled Content Claims: relationship-lists/recycled-content-claims.md
  - Controlled Lists:
    - Definition: controlled-lists/index.md
    - Care Label Sources: controlled-lists/care-label-sources.md
    - Component Disruptors: controlled-lists/component-disruptors.md
    - Certification Sources: controlled-lists/certification-sources.md
    - Deposit Return Schemes: controlled-lists/deposit-return-schemes.md
    - End of Life Routes: controlled-lists/end-of-life-routes.md
    - External Identifiers: controlled-lists/external-identifiers.md
    - Fashion and Textile Product Disruptors: controlled-lists/product-disruptors.md
    - Flexibility: controlled-lists/flexibility.md
    - Functions: controlled-lists/functions.md
    - Material Purposes: controlled-lists/material-purposes.md
    - Material Types: controlled-lists/material-types.md
    - Measures: controlled-lists/measures.md
    - Opacities: controlled-lists/opacities.md
    - Recyclability Sources: controlled-lists/recyclability-sources.md
    - Recycled Content Evidence Types: controlled-lists/recycled-content-evidence-types.md
    - Reuse Systems: controlled-lists/reuse-systems.md
    - Shapes: controlled-lists/shapes.md
  # - Supporting Files: 7_Supporting_Files/7_2_Example_Files.md
  # - Governance: 8_Governance/8_1_Governance.md
  - Licence: licence/index.md
  # - Glossary: 11_Glossary/11_000_Glossary.md
  - Change Log: change-log/index.md

extra:
  status:
    new: Added in this version
    updated: Updated in this version
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/opendatamcr
      name: ODM on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/opendatamcr
      name: ODM on LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/OpenDataManchester
      name: ODM on GitHub
    - icon: fontawesome/brands/vimeo
      link: https://vimeo.com/opendatamcr
      name: ODM on Vimeo
    - icon: octicons/calendar-16
      link: https://www.eventbrite.co.uk/o/open-data-manchester-2263648391
      name: ODM Events
    - icon: fontawesome/solid/globe
      link: https://www.opendatamanchester.org.uk/
      name: ODM Website
edit_uri: ""
markdown_extensions:
  - admonition
  - codehilite
  - smarty
  - meta
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: True
  - tables

# Additional styling
extra_css:
  - stylesheets/extra.css